module.exports = {
    a: [
        ' XXX ',
        'X   X',
        'XXXXX',
        'X   X',
        'X   X',
    ],
    b: [
        'XXXX ',
        'X   X',
        'XXXX ',
        'X   X',
        'XXXX ',
    ],
    c: [
        ' XXXX',
        'X    ',
        'X    ',
        'X    ',
        ' XXXX',
    ],
    d: [
        'XXXX ',
        'X   X',
        'X   X',
        'X   X',
        'XXXX ',
    ],
    e: [
        'XXXXX',
        'X    ',
        'XXX  ',
        'X    ',
        'XXXXX',
    ],
    f: [
        'XXXXX',
        'X    ',
        'XXX  ',
        'X    ',
        'X    ',
    ],
    g: [
        ' XXX ',
        'X    ',
        'X  XX',
        'X   X',
        ' XXX ',
    ],
    h: [
        'X   X',
        'X   X',
        'XXXXX',
        'X   X',
        'X   X',
    ],
    i: [
        'XXXXX',
        '  X  ',
        '  X  ',
        '  X  ',
        'XXXXX',
    ],
    j: [
        'XXXXX',
        '  X  ',
        '  X  ',
        'X X  ',
        ' X   ',
    ],
    k: [
        'X   X',
        'X  X ',
        'XXX  ',
        'X  X ',
        'X   X',
    ],
    l: [
        'X    ',
        'X    ',
        'X    ',
        'X    ',
        'XXXXX',
    ],
    m: [
        'X   X',
        'XX XX',
        'X X X',
        'X   X',
        'X   X',
    ],
    n: [
        'X   X',
        'XX  X',
        'X X X',
        'X  XX',
        'X   X',
    ],
    o: [
        ' XXX ',
        'X   X',
        'X   X',
        'X   X',
        ' XXX ',
    ],
    p: [
        'XXXX ',
        'X   X',
        'XXXX ',
        'X    ',
        'X    ',
    ],
    q: [
        ' XX  ',
        'X  X ',
        'X  X ',
        'X  X ',
        ' XXXX',
    ],
    r: [
        'XXXX ',
        'X   X',
        'XXXX ',
        'X  X ',
        'X   X',
    ],
    s: [
        ' XXXX',
        'X    ',
        ' XXX ',
        '    X',
        'XXXX ',
    ],
    t: [
        'XXXXX',
        '  X  ',
        '  X  ',
        '  X  ',
        '  X  ',
    ],
    u: [
        'X   X',
        'X   X',
        'X   X',
        'X   X',
        ' XXX ',
    ],
    v: [
        'X   X',
        'X   X',
        'X   X',
        ' X X ',
        '  X  ',
    ],
    w: [
        'X   X',
        'X   X',
        'X X X',
        'XX XX',
        'X   X',
    ],
    x: [
        'X   X',
        ' X X ',
        '  X  ',
        ' X X ',
        'X   X',
    ],
    y: [
        'X   X',
        'X   X',
        ' XXX ',
        '  X  ',
        '  X  ',
    ],
    z: [
        'XXXXX',
        '   X ',
        '  X  ',
        ' X   ',
        'XXXXX',
    ],
    '!': [
        '  X  ',
        '  X  ',
        '  X  ',
        '     ',
        '  X  ',
    ],
    '.': [
        '     ',
        '     ',
        '     ',
        '     ',
        '  X  ',
    ],
    '?': [
        ' XXX ',
        'X   X',
        '  XX ',
        '     ',
        '  X  ',
    ],
    ' ': [
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
    ],
    '@': [
        'XXXXX',
        'X   X',
        'X XXX',
        'X X X',
        'X XXX',
    ],
};
